### ISSUE TITLE
Specifying the random seed

### ISSUE THREAD

**Issue by davebellows** [prowlett/nimsticks#7]
I have a peculiar project that I'm working on where I use nimsticks outside of the context of the game. For this application I need to be able to set the seed for the prng in order to get the exact same shapes of the sticks when desired. I don't really have any idea how to do this as my understanding of the code is limited. 

I also understand that this is a peculiar request so I'm not counting on it being worth the effort to change the package just for me.

**Comment by prowlett** [comment]
The randomisation is done with [lcg](https://www.ctan.org/pkg/lcg/) and you can set the seed using `\reinitrand` from that package. The `seed` is supposed to be a number from 1 to 2^31 - 1, otherwise the package will use a combination of the time, page number and line number to make the seed. So if you reset the randomisation to the same `seed` before running `\drawnimstick` or `\nimgame` you'll get the same look to the sticks.

```
\documentclass{article}
\usepackage{nimsticks}

\begin{document}
    \reinitrand[first=-100,last=100,seed=1]
    \nimgame{3,4,5}
    
    \reinitrand[first=-100,last=100,seed=1]
    \nimgame{3,4,5}
    
\end{document}
```

I had a similar problem when using `\only` from `beamer`, in that the sticks appeared to move on what should appear to be the same slide. For example, this produces one slide with a reveal of "Text" which should have identical Nim sticks but doesn't. 

```
\documentclass{beamer}
\usepackage{nimsticks}
\begin{document}    
    \begin{frame}
        \nimgame{2,3,4} \only<2>{Text}
    \end{frame}
\end{document}
```

The fix is to reset the seed using `\reinitrand` within the frame, so that this is reset every time `\only` is called. This produces a slide where the sticks don't appear to move as the "Text" is revealed.

```
\documentclass{beamer}
\usepackage{nimsticks}
\begin{document}    
    \begin{frame}
        \reinitrand[first=-100,last=100,seed=123]\nimgame{2,3,4} \only<2>{Text}
    \end{frame}
\end{document}
```

By the way, `\reinitrand` can also be used to make the sticks wobble more or less, by changing the numbers `-100` and `100`. For example, try this:

```
\documentclass{article}
\usepackage{nimsticks}

\begin{document}
    \nimgame{3,4,5}
    
    \reinitrand[first=-10,last=10,seed=0]
    \nimgame{3,4,5}
    
    \reinitrand[first=-1000,last=1000,seed=0]
    \nimgame{3,4,5}
    
\end{document}
```

I will leave this open because it'd be good to mention this in the documentation.

**Comment by davebellows** [comment]
Perfect, thank you, the `\reinitrand` command was what I needed.
